# Generated by Django 3.0.7 on 2020-06-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='myinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=20)),
                ('contact', models.IntegerField(max_length=10)),
                ('objective', models.CharField(max_length=500)),
            ],
        ),
    ]
