# Generated by Django 3.0.7 on 2020-06-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_myinfo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myinfo',
            name='email',
            field=models.EmailField(max_length=40),
        ),
    ]
