# Generated by Django 3.0.7 on 2020-06-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200612_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinfo',
            name='img',
            field=models.ImageField(default='', upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='myinfo',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
